scrum/lkapp/urls.py
from django.urls import path

import lkapp.views as lkapp

app_name = "lkapp"

urlpatterns = [
    # Профиль
    path("profile/<int:pk>/", lkapp.my_profile, name="my_profile"),
    path("profile/<int:pk>/update", lkapp.profile_update, name="profile_update"),
    path("profile/<int:pk>/delete", lkapp.delete_user, name="delete_user"),
    path("profile/<int:pk>/set_email_settings", lkapp.set_mail_settting_switcher, name="switch_email_settings"),
    # Ajax-mail_checked
    path("profile/<int:pk>/switch_email_settings_ajax", lkapp.set_mail_settting_switcher,
         name="switch_email_settings_ajax"),
    # Статьи/Черновики
    path("post/create/", lkapp.post_creation, name="post_creation"),
    path("myposts/", lkapp.my_posts, name="my_posts"),
    path("myposts/published", lkapp.my_posts_ajax, name="published"),
    path("myposts/moderation", lkapp.my_posts_ajax, name="moderation"),
    path("myposts/correction", lkapp.my_posts_ajax, name="correction"),
    path("myposts/archive", lkapp.my_posts_ajax, name="archive"),
    path("myposts/myposts", lkapp.my_posts_ajax, name="myposts_ajax"),
    path("draft/", lkapp.my_drafts, name="drafts"),
    path("draft/<int:pk>/", lkapp.preview_draft, name="read_draft"),
    path("draft/<int:pk>/moderation", lkapp.publicating_post,
         name="go_on_moderation_post"),
    path("draft/<int:pk>/delete", lkapp.delete_drafts, name="delete_drafts"),
    path("myposts/<int:pk>/", lkapp.preview_post, name="preview_post"),
    path("myposts/<int:pk>/publicate",
         lkapp.publicating_post, name="publicate_post"),
    path("myposts/<int:pk>/deactivate",
         lkapp.archivating_post, name="deactivate_post"),
    path("posts_moderation/", lkapp.posts_on_moderation,
         name="posts_for_moderation"),
    path("post_moderation/<int:pk>/",
         lkapp.post_moderation, name="post_moderation"),
    path(
        "post_moderation/<int:pk>/correction/",
        lkapp.set_article_status_correction,
        name="set_article_status_correction",
    ),
    path(
        "post_moderation/<int:pk>/published/", lkapp.set_article_status_published, name="set_article_status_published"
    ),
    path("myposts/<int:pk>/edit", lkapp.edit_post, name="edit_post"),
    path("draft/<int:pk>/edit", lkapp.edit_draft, name="edit_draft"),

    # Уведомления
    path("my_alerts/", lkapp.my_alerts, name="my_alerts"),
    path("my_alerts/comment_alerts", lkapp.my_alerts, name="comment_alerts"),
    path("my_alerts/grade_alerts", lkapp.my_alerts, name="grade_alerts"),
    path("my_alerts/moder_alerts", lkapp.my_alerts, name="moder_alerts"),
    path("my_alerts/subscribe_alerts", lkapp.my_alerts, name="subscribe_alerts"),
    # Кнопки уведомлений

    # ajax меню блока Alerts++
    path("my_alerts/my_alerts_ajax", lkapp.my_alerts_ajax, name="my_alerts_ajax"),
    path("my_alerts/comment_alerts_ajax",
         lkapp.my_alerts_ajax, name="comment_alerts_ajax"),
    path("my_alerts/grade_alerts_ajax",
         lkapp.my_alerts_ajax, name="grade_alerts_ajax"),
    path("my_alerts/moder_alerts_ajax",
         lkapp.my_alerts_ajax, name="moder_alerts_ajax"),
    path("my_alerts/subscribe_alerts_ajax",
         lkapp.my_alerts_ajax, name="subscribe_alerts_ajax"),
    # ajax меню блока Alerts--

    path("delete_all_alerts/", lkapp.delete_all_alerts, name="delete_all_alerts"),
    path("delete_read_alerts/", lkapp.delete_read_alerts,
         name="delete_read_alerts"),
    path("delete_alert/<int:pk>/", lkapp.delete_alert, name="delete_alert"),
    path("mark_as_read/<int:pk>/", lkapp.mark_as_read, name="mark_as_read"),

    # Жалобы
    path("complains/", lkapp.my_complains, name="my_complains"),
    path("complains/complains", lkapp.my_complains_ajax, name="my_complains_ajax"),
    path("complains/complain_posts", lkapp.my_complains_post_ajax, name="my_complains_post_ajax"),
    path("complains/complain_comments", lkapp.my_complains_comments_ajax, name="my_complains_comments_ajax"),
    path("complains/moderation/<int:pk>/", lkapp.complain_moderation, name="complain_moderation"),
    path("complains/moderation/<int:pk>/denied/", lkapp.set_complain_status_denied,
         name="set_complain_status_denied"),
    path("complains/moderation/<int:pk>/approve/", lkapp.set_complain_status_approve,
         name="set_complain_status_approve"),
    # Подписки
    path("mysubscribes/", lkapp.my_subscribes, name="my_subscribes"),
]

scrum/mainapp/urls.py
from django.urls import path

from .views import (
    main,
    read_post,
    hubs,
    like_post,
    dislike_post,
    comments_count,
    allert_counter,
    profile_page,
    follow,
    like_author,
    dislike_author,
    post_complaint,
    comment_complaint,
    search, get_audio_name, get_audio_block,
    set_user_ban_status,
    set_user_unban_status, like_comment, dislike_comment, comment_ajax,like_dislike_comment_ajax, regenerate_audio
)

app_name = "mainapp"

urlpatterns = [
    # Страница автора
    path("user/<int:pk>", profile_page, name="profile_page"),

    # Оценка автора
    path("user/like/<int:pk>", like_author, name="like_author"),
    path("user/dislike/<int:pk>", dislike_author, name="dislike_author"),

    # Оценка автора (ajax)
    path("user/like/<int:pk>/like_user_count",
         like_author, name="like_author_ajax"),
    path("user/dislike/<int:pk>/dislike_user_count",
         dislike_author, name="dislike_author_ajax"),

    # Подписка
    path("user/follow/<int:pk>", follow, name="follow"),

    # Главная + страницы Хабов + сортировка
    path("", main, name="index"),
    path("index/<str:sorted_by>/", main, name="index_sorted"),
    path("category/<slug:slug>/", hubs, name="category"),
    path("index/<slug:slug>/<str:sorted_by>/", hubs, name="category_sorted"),

    # Страница статьи
    path("post/<int:pk>/", read_post, name="read_post"),

    # Оценка статьи
    path("post/<int:pk>/like_count", like_post, name="like_count"),
    path("post/<int:pk>/dislike_count", dislike_post, name="dislike_count"),

    # Комментарии
    path("post/<int:pk>/comments_count", comments_count, name="comments_count"),
    path("post/<int:pk>/get_comment", comment_ajax, name="get_comment"),
    path("post/<int:pk>/like_dislike_comment", like_dislike_comment_ajax, name="like_dislike_comment"),    

    # Жалоба на комментарий
    path("post/<int:pk>/comment_complaint",
         comment_complaint, name="comment_complaint"),

    # Оценка комментария
    path("post/<int:pk>/like_comment", like_comment, name="like_comment"),
    path("post/<int:pk>/dislike_comment", dislike_comment, name="dislike_comment"),


    # Счетчик уведомлений
    path("post/allert_counter", allert_counter, name="allert_counter"),

    # Поиск
    path("post/<int:pk>/post_complaint", post_complaint, name="post_complaint"),
    path("search/", search, name="search"),

    # Аудио
    path("media/article_audio/<str:audio_name>/", get_audio_name, name="get_audio_name"),
    path("post/get_audio_block/", get_audio_block, name="get_audio_block"),
    path("post/regenerate_audio/", regenerate_audio, name="regenerate_audio"),
    
    # Бан
    path("user/ban/", set_user_ban_status,
         name="set_user_ban_status"),
    path("user/<int:pk>/unban/", set_user_unban_status,
         name="set_user_unban_status"),
]

scrum/scrum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('my_admin/', include('adminapp.urls', namespace='my_admin')),
    path('my_lk/', include('lkapp.urls', namespace='my_lk')),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

scrum/lkapp/views.py
import os
from datetime import datetime
from tzlocal import get_localzone
import pytz
from django.utils import timezone

from django.conf import settings
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from authapp.helpers import deactivate_user
from authapp.models import User
from authapp.views import logout
from lkapp.forms import UserProfileForm, PostCreationForm
from lkapp.helpers.alerts import get_alerts, get_mail_settings, set_mail_settings
from lkapp.helpers.alerts.alert import AlertFrontHandler, count_alerts
from lkapp.helpers.rating_author import get_rate_author
from lkapp.helpers.ban_of_user.ban import ban_is_active, get_ban_obj
from lkapp.helpers.ban_of_user.user_ban import FOREVER
from mainapp.helpers import get_current_user
from mainapp.helpers.article.article import get_category_list, get_article
from mainapp.helpers.scores.score_author import get_count_user_likes, get_count_user_dislikes
from mainapp.models import Article
from django.views.decorators.csrf import csrf_exempt
from mainapp.models import Complaint
from .helpers import (
    get_hash,
    hash_equality,
)
from .helpers.complains import (
    set_complain_status,
    get_complains_comments_on_moderation,
    get_complains_posts_on_moderation,
    get_complains_on_moderation,
)
from .helpers.posts.my_posts import (
    get_articles,
    get_articles_on_moderation,
    publicate_post,
    delete_draft,
    archivate_post,
    set_article_status,
)
from .models import Alert


@user_passes_test(lambda x: x.is_authenticated)
def my_profile(request, pk):
    timezone.activate(pytz.timezone(str(get_localzone())))
    if request.user.id != pk:
        return HttpResponseRedirect(reverse("authapp:login"))
    else:
        title = "ЛК|Профиль"
        content = {
            "title": title,
            "user": get_current_user(request),
            "categories": get_category_list,
            "media_url": settings.MEDIA_URL,
            "alert": count_alerts(request),
            "rate_author": get_rate_author(pk),
            "count_likes": get_count_user_likes(pk),
            "count_dislikes": get_count_user_dislikes(pk),
            "email_setting": get_mail_settings(request.user.id),
            "ban": ban_is_active(pk),
            "ban_info": get_ban_obj(pk),
        }

        if ban_is_active(pk):
            ban_obj = get_ban_obj(pk)
            create_time = ban_obj.created_at
            end_time = ban_obj.ban_end_time
            delta = end_time - create_time
            result = delta.days * 1440 + 639
            print(result)
            if result == FOREVER:
                content['ban_time'] = 'Бессрочный'
            else:
                content['ban_time'] = ban_obj.ban_end_time

    return render(request, "lkapp/profile.html", content)


@user_passes_test(lambda x: x.is_authenticated)
def profile_update(request, pk):
    user = get_object_or_404(User, pk=int(pk))
    if request.user.id != pk:
        return HttpResponseRedirect(reverse("authapp:login"))
    else:
        if request.method == "POST":
            profile_form = UserProfileForm(request.POST, request.FILES, instance=user)
            if profile_form.is_valid():
                profile_form.save()
                return HttpResponseRedirect(
                    reverse(
                        "my_lk:my_profile",
                        kwargs={
                            "pk": user.id,
                        },
                    )
                )
        else:
            profile_form = UserProfileForm(instance=user)

    context = {
        "title": "пользователи/редактирование",
        "form": profile_form,
        "user": user,
        "categories": get_category_list,
        "alert": count_alerts(request),
    }

    return render(request, "lkapp/update_profile.html", context)


@user_passes_test(lambda x: x.is_authenticated)
def delete_user(request):
    deactivate_user(request)
    return logout(request)


def post_creation(request):
    user = get_current_user(request)
    title = "ЛК|Создание поста"

    if ban_is_active(request.user.id):
        return HttpResponseRedirect(reverse("lkapp:my_profile", kwargs={"pk": request.user.id}))
    else:
        if request.method == "POST":
            post_creation_form = PostCreationForm(request.POST, request.FILES)
            if post_creation_form.is_valid():
                new_post = Article()
                new_post.title = post_creation_form.cleaned_data["title"]
                new_post.preview = post_creation_form.cleaned_data["preview"]
                new_post.body = post_creation_form.cleaned_data["body"]
                new_post.image = post_creation_form.cleaned_data["image"]
                new_post.category = post_creation_form.cleaned_data["category"]
                new_post.tag = post_creation_form.cleaned_data["tag"]
                new_post.author = user
                new_post.save()
                # после сохранения черновика переход на страницу с черновиками
                return HttpResponseRedirect(reverse("lkapp:drafts"))
            else:
                print("INVALID")
        else:
            post_creation_form = PostCreationForm()

        content = {
            "title": title,
            "current_datetime": datetime.now(),
            "form": post_creation_form,
            "author": f"{user.first_name} {user.last_name}",
            "categories": get_category_list,
            "alert": count_alerts(request),
        }
        return render(request, "lkapp/create_post_page.html", content)


@login_required()
def my_posts(request):
    timezone.activate(pytz.timezone(str(get_localzone())))
    title = "Мои посты"
    content = {
        "title": title,
        "articles": get_articles(request, "-updated_at"),
        "categories": get_category_list,
        "media_url": settings.MEDIA_URL,
        "alert": count_alerts(request),
        "ban": ban_is_active(request.user.id),
        "ban_info": get_ban_obj(request.user.id),
    }
    return render(request, "lkapp/my_posts.html", content)


@login_required()
def my_subscribes(request):
    title = "Мои подписки"
    user = get_current_user(request)
    subscribes = user.follows.all()
    subscribers = user.followers.all()
    content = {
        "title": title,
        "user": user,
        "subscribes": subscribes,
        "subscribers": subscribers,
        "categories": get_category_list,
        "media_url": settings.MEDIA_URL,
        "alert": count_alerts(request),
    }
    return render(request, "lkapp/my_subscribes.html", content)


@login_required
def my_posts_ajax(request):
    timezone.activate(pytz.timezone(str(get_localzone())))
    title = "Мои посты"
    content = {
        "title": title,
        "articles": get_articles(request),
        "categories": get_category_list,
        "media_url": settings.MEDIA_URL,
        "ban": ban_is_active(request.user.id),
        "ban_info": get_ban_obj(request.user.id),
    }
    print(request)
    return render(request, "lkapp/includes/article_list.html", content)
    # return render(request, "lkapp/my_posts.html", content)


@login_required()
def posts_on_moderation(request):
    timezone.activate(pytz.timezone(str(get_localzone())))
    title = "Посты на модерации"
    content = {
        "title": title,
        "articles": get_articles_on_moderation(request, "-updated_at"),
        "categories": get_category_list,
        "media_url": settings.MEDIA_URL,
        "alert": count_alerts(request),
    }
    return render(request, "lkapp/posts_on_moderation.html", content)


@login_required()
def my_drafts(request):
    timezone.activate(pytz.timezone(str(get_localzone())))
    title = "Мои черновики"
    content = {
        "title": title,
        "drafts": get_articles(request, "-updated_at"),
        "categories": get_category_list,
        "media_url": settings.MEDIA_URL,
        "alert": count_alerts(request),
        "ban": ban_is_active(request.user.id),
        "ban_info": get_ban_obj(request.user.id),
    }
    return render(request, "lkapp/my_drafts.html", content)


@login_required()
def preview_draft(request, pk):
    if request.user.id != get_article(pk).author_id:
        title = "Ошибка доступа"
        content = {
            "title": title,
            "categories": get_category_list,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "lkapp/errors/access_error.html", content)
    else:
        article = get_article(pk, status="draft")
        title = f"Черновик - {article.title}"
        content = {
            "title": title,
            "article": article,
            "user": get_current_user(request),
            "categories": get_category_list,
            "media_url": settings.MEDIA_URL,
            "alert": count_alerts(request),
        }
        return render(request, "lkapp/preview_draft.html", content)


@login_required()
def preview_post(request, pk):
    if request.user.id != get_article(pk).author_id:
        return HttpResponseRedirect(reverse("authapp:login"))
    else:
        article = get_article(pk)
        title = f"{article.title}"
        content = {
            "title": title,
            "article": article,
            "user": get_current_user(request),
            "categories": get_category_list,
            "media_url": settings.MEDIA_URL,
            "alert": count_alerts(request),
            "audio_url": os.path.join("\\media\\article_audio", article.audio_name),
        }
        return render(request, "lkapp/preview_post.html", content)


@user_passes_test(lambda x: x.is_authenticated)
def publicating_post(request, pk):
    post_status = get_article(pk).status
    user_ban = ban_is_active(request.user.id)
    if user_ban:

scrum/lkapp/templates/lkapp/my_alerts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lkapp.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'style/alerts.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'style/menu.css' %}" />
{% endblock %}

{% block content %}
<!-- Основной блок -->
<div class="container-2 w-container mb-5" style="margin-left: auto; margin-right: auto; max-width: 960px;">
    <div class="d-block bg-light shadow rounded mb-5 p-5">
        <!-- Заголовок вкладки -->
        <h4 class="d-block mb-5">Оповещения</h4>
        <!-- Меню фильтров -->
        {% block filter_alerts %}
        {% include 'lkapp/includes/inc_filter_alerts.html' %}
        {% endblock %}
        <!-- Кнопки уведомлений -->
        {% if alerts %}
        <div class="neg_btns mb-3">
            <a class="btn btn-sm btn-outline-danger text-center" role="button"
                href="{% url 'my_lk:delete_all_alerts' %}">Удалить все оповещения</a>
            <a class="btn btn-sm btn-outline-danger text-center" role="button"
                href="{% url 'my_lk:delete_read_alerts' %}">Удалить все прочитанные оповещения</a>
        </div>
        {% endif %}
        <!-- Блок с уведомлениями -->
        <div id='alertlistblock' name = {{ request.resolver_match.url_name  }}>
        {% include 'lkapp/includes/alert_list.html' %}
        </div>
    </div>
</div>

{% block javascript %}
<script>
    var elems = $("[id^='filteralerts']")
    elems.on("click", function () {
        var type_post = this.attributes.name.value
        var url = ''
        if (type_post == 'my_alerts') url = "{% url 'my_lk:my_alerts_ajax' %}"
        if (type_post == 'comment_alerts') url = "{% url 'my_lk:comment_alerts_ajax' %}"
        if (type_post == 'grade_alerts') url = "{% url 'my_lk:grade_alerts_ajax' %}"
        if (type_post == 'moder_alerts') url = "{% url 'my_lk:moder_alerts_ajax' %}"
        if (type_post == 'subscribe_alerts') url = "{% url 'my_lk:subscribe_alerts_ajax' %}"
        $.ajax({
            data: $(this).serialize(), // получаяем данные формы
            url: url,
            // если успешно, то
            success: function (response) {
                $('.menu_filters').removeClass('active_filters shadow rounded')
                $('.menu_filters').css('color', '');
                $('.' + type_post).css('color', '#000');
                $('.' + type_post).addClass('active_filters shadow rounded')
                $('#alertlistblock').empty();
                $('#alertlistblock').html(response);
                document.getElementById('alertlistblock').setAttribute('name', type_post);
            },
            // если ошибка, то
            error: function (response) {
                // предупредим об ошибке
                console.log(response.responseJSON.errors)
            }

        })
    });

    function read_redirect_ajax(url, type_docs, url_target = ''){
        $.ajax({
            url: url,  
            method: 'post',
            dataType: 'text',             
            data: {type_post: type_docs},
            // если успешно, то
            success: function (response) {
                console.log('ok')
                if (url_target == ''){
                    $('#alertlistblock').empty();
                    $('#alertlistblock').html(response);               
                }
                else {
                    window.location.href = url_target    
                }
            },
            // если ошибка, то
            error: function (response) {
                // предупредим об ошибке
                console.log(response.responseJSON.errors)
            }
        })  
    } 
    
    $("#alertlistblock").click(function () {
        if  (event.target.tagName == "EM"){
            var target_el = event.target.parentNode.parentElement
            if (target_el.id.length){
                if (target_el.id == 'redirect' ){
                    var url = target_el.attributes.name_read.value
                    var url_target = target_el.attributes.name.value
                    var type_docs = document.getElementById('alertlistblock').attributes.name.value
                    console.log('1',url, url_target, type_docs)
                    read_redirect_ajax(url, type_docs, url_target)
                }
            }
        } else {
            if ($(event.target.attributes.id).length){
                if (((event.target.tagName == "P") || (event.target.tagName == "A")) && (event.target.attributes.id.value == 'redirect')){
                    var url = event.target.attributes.name_read.value
                    var url_target = event.target.attributes.name.value
                    var type_docs = document.getElementById('alertlistblock').attributes.name.value
                    read_redirect_ajax(url, type_docs, url_target)
                }
                else if ((event.target.tagName == "P") && ((event.target.attributes.id.value == 'read_alert') || (event.target.attributes.id.value == 'del_alert'))){
                    var url = event.target.attributes.name.value
                    var type_docs = document.getElementById('alertlistblock').attributes.name.value
                    read_redirect_ajax(url, type_docs)
                }
            }
        }

     

    } )   ;

</script>
{% endblock javascript %}

{% endblock %}

scrum/lkapp/templates/lkapp/my_complains.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lkapp.css' %}" />
{% endblock %}

{% block user_menu %}
{% include 'lkapp/includes/inc__lk_menu.html' %}
{% endblock %}

{% block content %}
<!-- Основной блок -->
<div class="container-2 w-container mt-5 mb-5" style="margin-left: auto; margin-right: auto; max-width: 960px;">
    <div class="d-block bg-light shadow rounded mb-5 p-5">
        <!-- Заголовок вкладки -->
        <h4 class="d-block mb-5">Жалобы</h4>
<!--         Блок с подвкладками-->
        {% block filter_complains %}
        {% include 'lkapp/includes/filters_complains.html' %}
        {% endblock %}
        <div id='complainblock'>
            {% include 'lkapp/includes/complain_list.html' %}
        </div>
    </div>
</div>

{% block javascript %}
<script>
    var elems = $("[id^='filtercomplain']")
    elems.on("click", function () {
        var type_post = this.attributes.name.value
        console.log(type_post)
        var url = ''
        if (type_post == 'complains') url = "{% url 'my_lk:my_complains_ajax' %}"
        if (type_post == 'complain_posts') url = "{% url 'my_lk:my_complains_post_ajax' %}"
        if (type_post == 'complains_comments') url = "{% url 'my_lk:my_complains_comments_ajax' %}"
        $.ajax({
            data: $(this).serialize(), // получаяем данные формы
            url: url,
            // если успешно, то
            success: function (response) {
                $('.menu_filters').removeClass('active_filters shadow rounded')
                $('.menu_filters').css('color', '');
                $('.' + type_post).css('color', '#000');
                $('.' + type_post).addClass('active_filters shadow rounded')
                $('#complainblock').empty();
                $('#complainblock').html(response);
            },
            // если ошибка, то
            error: function (response) {
                // предупредим об ошибке
                console.log(response.responseJSON.errors)
            }

        })
    });
</script>
{% endblock javascript %}

{% endblock %}

scrum/lkapp/templates/lkapp/my_drafts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lkapp.css' %}" />
{% endblock %}

{% block user_menu %}
{% include 'lkapp/includes/inc__lk_menu.html' %}
{% endblock %}

{% block content %}
<!-- Основной блок -->
<div class="container-2 w-container mt-5 mb-5" style="margin-left: auto; margin-right: auto; max-width: 960px;">
    <div class="d-block bg-light shadow rounded mb-5 p-5">
        <!-- Заголовок вкладки -->
        <h4 class="d-block mb-5">Мои черновики</h4>
        <div class="btns d-flex flex-wrap mt-3 justify-content-between mb-5" style="padding: 0;">
            <div class="d-flex flex-wrap">
                <a class="{% if ban %} disabled {% endif %} btn btn-sm btn-outline-dark me-2 p-1 btn_blue text-center shadow {% if request.path == '/my_lk/post/create/' %} active {% endif %}"
                    href="{% url 'my_lk:post_creation' %}" role="button"> Новый черновик
                </a>
            </div>
        </div>
        <!-- Блок с черновиками -->
        {% for draft in drafts %}
        <div style="word-break: break-word;" class="d-flex flex-column table_post shadow rounded mb-3 p-2 table-responsive">
            
            <!-- Таблица -->
            <table class="table table-borderless mb-0" style="font-size: 12px;">
                <tr>
                    <td class="d-flex align-items-center" style="font-weight: bold;">
                        <img class="me-3" src="{% static 'vendor/img_for_alerts/file-post.svg' %}" alt="Иконка" width="23"
                            height="23">
                        <p class="me-2">{{ draft.updated_at }}</p>
                        <p class="text-capitalize me-2">{{ draft.category }}</p>
                    </td>
                    <td class="d-flex flex-column flex-wrap mb-2">
                        <h5>{{ draft.title }}</h5>
                        <p>{{ draft.preview }}</p>
                    </td>
                </tr>
            </table>

            <!-- Блок с кнопками -->
            <div class="btns_drafts d-flex justify-content-between m-2 mb-0">
                <div class="positive_btns">
                    <a href="{% url 'my_lk:go_on_moderation_post' draft.id %}"
                        class="{% if ban %} disabled {% endif %} btn btn-sm shadow btn_blue text-center" role="button">
                        <div class="btns_hover">
                            <p class="m-0">Опубликовать</p>
                        </div>
                    </a>
                    <a href="{% url 'lkapp:edit_draft' draft.id %}" class="btn btn-sm shadow btn_blue text-center"
                        role="button">
                        <div class="btns_hover">
                            <p class="m-0">Редактировать</p>
                        </div>
                    </a>
                    <a href="{% url 'my_lk:read_draft' draft.id %}" class="btn btn-sm shadow btn_blue text-center"
                        role="button">
                        <div class="btns_hover">
                            <p class="m-0">Предпросмотр</p>
                        </div>
                    </a>
                </div>

                <div class="negative_btns">
                    <a href="{% url 'my_lk:delete_drafts' draft.id %}" class="btn btn-sm btn_archive shadow text-center"
                        role="button">
                        <div class="btns_hover">
                            <p class="m-0">Удалить</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}