scrum/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("register/", authapp.register, name="register"),
    path("delete/", authapp.delete, name="delete"),
]

scrum/lkapp/urls.py
from django.urls import path

import lkapp.views as lkapp

app_name = "lkapp"

urlpatterns = [
    # Профиль
    path("profile/<int:pk>/", lkapp.my_profile, name="my_profile"),
    path("profile/<int:pk>/update", lkapp.profile_update, name="profile_update"),
    path("profile/<int:pk>/delete", lkapp.delete_user, name="delete_user"),
    path("profile/<int:pk>/set_email_settings", lkapp.set_mail_settting_switcher, name="switch_email_settings"),
    # Ajax-mail_checked
    path("profile/<int:pk>/switch_email_settings_ajax", lkapp.set_mail_settting_switcher,
         name="switch_email_settings_ajax"),
    # Статьи/Черновики
    path("post/create/", lkapp.post_creation, name="post_creation"),
    path("myposts/", lkapp.my_posts, name="my_posts"),
    path("myposts/published", lkapp.my_posts_ajax, name="published"),
    path("myposts/moderation", lkapp.my_posts_ajax, name="moderation"),
    path("myposts/correction", lkapp.my_posts_ajax, name="correction"),
    path("myposts/archive", lkapp.my_posts_ajax, name="archive"),
    path("myposts/myposts", lkapp.my_posts_ajax, name="myposts_ajax"),
    path("draft/", lkapp.my_drafts, name="drafts"),
    path("draft/<int:pk>/", lkapp.preview_draft, name="read_draft"),
    path("draft/<int:pk>/moderation", lkapp.publicating_post,
         name="go_on_moderation_post"),
    path("draft/<int:pk>/delete", lkapp.delete_drafts, name="delete_drafts"),
    path("myposts/<int:pk>/", lkapp.preview_post, name="preview_post"),
    path("myposts/<int:pk>/publicate",
         lkapp.publicating_post, name="publicate_post"),
    path("myposts/<int:pk>/deactivate",
         lkapp.archivating_post, name="deactivate_post"),
    path("posts_moderation/", lkapp.posts_on_moderation,
         name="posts_for_moderation"),
    path("post_moderation/<int:pk>/",
         lkapp.post_moderation, name="post_moderation"),
    path(
        "post_moderation/<int:pk>/correction/",
        lkapp.set_article_status_correction,
        name="set_article_status_correction",
    ),
    path(
        "post_moderation/<int:pk>/published/", lkapp.set_article_status_published, name="set_article_status_published"
    ),
    path("myposts/<int:pk>/edit", lkapp.edit_post, name="edit_post"),
    path("draft/<int:pk>/edit", lkapp.edit_draft, name="edit_draft"),

    # Уведомления
    path("my_alerts/", lkapp.my_alerts, name="my_alerts"),
    path("my_alerts/comment_alerts", lkapp.my_alerts, name="comment_alerts"),
    path("my_alerts/grade_alerts", lkapp.my_alerts, name="grade_alerts"),
    path("my_alerts/moder_alerts", lkapp.my_alerts, name="moder_alerts"),
    path("my_alerts/subscribe_alerts", lkapp.my_alerts, name="subscribe_alerts"),
    # Кнопки уведомлений

    # ajax меню блока Alerts++
    path("my_alerts/my_alerts_ajax", lkapp.my_alerts_ajax, name="my_alerts_ajax"),
    path("my_alerts/comment_alerts_ajax",
         lkapp.my_alerts_ajax, name="comment_alerts_ajax"),
    path("my_alerts/grade_alerts_ajax",
         lkapp.my_alerts_ajax, name="grade_alerts_ajax"),
    path("my_alerts/moder_alerts_ajax",
         lkapp.my_alerts_ajax, name="moder_alerts_ajax"),
    path("my_alerts/subscribe_alerts_ajax",
         lkapp.my_alerts_ajax, name="subscribe_alerts_ajax"),
    # ajax меню блока Alerts--

    path("delete_all_alerts/", lkapp.delete_all_alerts, name="delete_all_alerts"),
    path("delete_read_alerts/", lkapp.delete_read_alerts,
         name="delete_read_alerts"),
    path("delete_alert/<int:pk>/", lkapp.delete_alert, name="delete_alert"),
    path("mark_as_read/<int:pk>/", lkapp.mark_as_read, name="mark_as_read"),

    # Жалобы
    path("complains/", lkapp.my_complains, name="my_complains"),
    path("complains/complains", lkapp.my_complains_ajax, name="my_complains_ajax"),
    path("complains/complain_posts", lkapp.my_complains_post_ajax, name="my_complains_post_ajax"),
    path("complains/complain_comments", lkapp.my_complains_comments_ajax, name="my_complains_comments_ajax"),
    path("complains/moderation/<int:pk>/", lkapp.complain_moderation, name="complain_moderation"),
    path("complains/moderation/<int:pk>/denied/", lkapp.set_complain_status_denied,
         name="set_complain_status_denied"),
    path("complains/moderation/<int:pk>/approve/", lkapp.set_complain_status_approve,
         name="set_complain_status_approve"),
    # Подписки
    path("mysubscribes/", lkapp.my_subscribes, name="my_subscribes"),
]

scrum/mainapp/urls.py
from django.urls import path

from .views import (
    main,
    read_post,
    hubs,
    like_post,
    dislike_post,
    comments_count,
    allert_counter,
    profile_page,
    follow,
    like_author,
    dislike_author,
    post_complaint,
    comment_complaint,
    search, get_audio_name, get_audio_block,
    set_user_ban_status,
    set_user_unban_status, like_comment, dislike_comment, comment_ajax,like_dislike_comment_ajax, regenerate_audio
)

app_name = "mainapp"

urlpatterns = [
    # Страница автора
    path("user/<int:pk>", profile_page, name="profile_page"),

    # Оценка автора
    path("user/like/<int:pk>", like_author, name="like_author"),
    path("user/dislike/<int:pk>", dislike_author, name="dislike_author"),

    # Оценка автора (ajax)
    path("user/like/<int:pk>/like_user_count",
         like_author, name="like_author_ajax"),
    path("user/dislike/<int:pk>/dislike_user_count",
         dislike_author, name="dislike_author_ajax"),

    # Подписка
    path("user/follow/<int:pk>", follow, name="follow"),

    # Главная + страницы Хабов + сортировка
    path("", main, name="index"),
    path("index/<str:sorted_by>/", main, name="index_sorted"),
    path("category/<slug:slug>/", hubs, name="category"),
    path("index/<slug:slug>/<str:sorted_by>/", hubs, name="category_sorted"),

    # Страница статьи
    path("post/<int:pk>/", read_post, name="read_post"),

    # Оценка статьи
    path("post/<int:pk>/like_count", like_post, name="like_count"),
    path("post/<int:pk>/dislike_count", dislike_post, name="dislike_count"),

    # Комментарии
    path("post/<int:pk>/comments_count", comments_count, name="comments_count"),
    path("post/<int:pk>/get_comment", comment_ajax, name="get_comment"),
    path("post/<int:pk>/like_dislike_comment", like_dislike_comment_ajax, name="like_dislike_comment"),    

    # Жалоба на комментарий
    path("post/<int:pk>/comment_complaint",
         comment_complaint, name="comment_complaint"),

    # Оценка комментария
    path("post/<int:pk>/like_comment", like_comment, name="like_comment"),
    path("post/<int:pk>/dislike_comment", dislike_comment, name="dislike_comment"),


    # Счетчик уведомлений
    path("post/allert_counter", allert_counter, name="allert_counter"),

    # Поиск
    path("post/<int:pk>/post_complaint", post_complaint, name="post_complaint"),
    path("search/", search, name="search"),

    # Аудио
    path("media/article_audio/<str:audio_name>/", get_audio_name, name="get_audio_name"),
    path("post/get_audio_block/", get_audio_block, name="get_audio_block"),
    path("post/regenerate_audio/", regenerate_audio, name="regenerate_audio"),
    
    # Бан
    path("user/ban/", set_user_ban_status,
         name="set_user_ban_status"),
    path("user/<int:pk>/unban/", set_user_unban_status,
         name="set_user_unban_status"),
]

scrum/scrum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('my_admin/', include('adminapp.urls', namespace='my_admin')),
    path('my_lk/', include('lkapp.urls', namespace='my_lk')),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

scrum/mainapp/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from django.forms import ModelForm

from .models import Comments


# Форма для комментария
class Add_Comment_Form(ModelForm):
    comment_text = forms.CharField(label='Написать комментарий',
                                   widget=CKEditorUploadingWidget(
                                       config_name='comment'))

    class Meta:
        model = Comments
        fields = ("comment_text",)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'comment-field'
            field.widget.attrs['placeholder'] = 'Ваш комментарий...'
            field.widget.attrs['name'] = 'text'
            self.fields['comment_text'].label = False

scrum/mainapp/templates/mainapp/includes/inc__articles_list.html
{% load static %}

<div class="infinite-container article_list">
    {% for post in posts %}
    <div class="infinite-item article_card shadow p-3 mb-5 bg-white rounded" id="{{ post.id }}">
        <div class="article_info">
            <div class="d-flex p-2 px-0 pe-2" id="authorRate">
                {% if post.author.author_rating >= 0 and post.author.author_rating < 4 %}
                <p class="d-flex align-items-center bg-danger rounded-circle text-light shadow m-0"
                   style="width: 36px; height: 36px;">
                    <b class="col-12 rateAuthor" style="text-align: center">{{ post.author.author_rating }}</b>
                </p>
                {% endif %}
                {% if post.author.author_rating >= 4 and post.author.author_rating < 7 %}
                <p class="d-flex align-items-center bg-warning rounded-circle text-light shadow m-0"
                   style="width: 36px; height: 36px;">
                    <b class="col-12 rateAuthor" style="text-align: center">{{ post.author.author_rating }}</b>
                </p>
                {% endif %}
                {% if post.author.author_rating >= 7 %}
                <p class="d-flex align-items-center bg-success rounded-circle text-light shadow m-0"
                   style="width: 36px; height: 36px;">
                    <b class="col-12 rateAuthor" style="text-align: center">{{ post.author.author_rating }}</b>
                </p>
                {% endif %}
            </div>
            <a href="{% url 'mainapp:profile_page' post.author.id %}"
               class="article_user d-flex align-items-center">
                {{ post.author }}
            </a>
            <p class="article_creation_data d-flex align-items-center m-0">
                {{ post.published_at }}
            </p>
        </div>
        <div class="article_chapters">
            <a href="{% url 'main:category' post.category.slug %}"
               class="article_chapter_link text-capitalize">{{ post.category }}
            </a>
        </div>
        <img src="{{ media_url }}{{ post.image }}" loading="lazy"
             class="article_image shadow bg-white rounded mx-auto d-block">
        <a href="{% url 'mainapp:read_post' post.id %}" class="article_heading">
            {{ post.title }}
        </a>
        <p class="article_text">
            {{ post.preview }}
        </p>
        <a href="{% url 'mainapp:read_post' post.id %}" class="article_button w-button shadow rounded">
            Читать полностью
        </a>
        {% include 'mainapp/includes/likes_comments_counter.html' %}
    </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item {% if not posts.has_previous %} disabled {% endif %}">
            <a class="page-link link_page"
               href="{% if posts.has_previous %} ?page={{ posts.previous_page_number }} {% endif %}"
               tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        {% for page in posts.paginator.page_range %}
            <li class="page-item">
                <a class="page-link link_page" href="?page={{ page }}" id="page_link">
                    {{ page }}</a>
            </li>
        {% endfor %}
        <li class="page-item {% if not posts.has_next %} disabled {% endif %}">
            <a class="page-link link_page"
               href="{% if posts.has_next %} ?page={{ posts.next_page_number }} {% endif %}">
                Next</a>
        </li>
    </ul>
</nav>

<!--<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>-->
<!--<script src="{% static 'js/infinite.min.js' %}"></script>-->
<!--<script src="{% static 'js/article_tape.js' %}"></script>-->
<script src="{% static 'js/current_page.js' %}"></script>
<script src="{% static 'js/rounding_rate.js' %}" defer></script>

scrum/mainapp/templates/mainapp/includes/inc__audio_block.html
{% load static %}

<dev id="audio_block" name="{% if 'article' in post.audio_name %}done{% else %}{{ post.id }}{% endif %}">
    {% if post.audio_name == "generating" %}
        <p class="fst-italic text-secondary">Аудиодорожка генерируется...</p>
    {% elif post.audio_name == "error" %}
        <p class="fst-italic text-secondary">Ошибка генерации аудиодорожки :(</p>
    {% elif post.audio_name == "" %}
        <p class="fst-italic text-secondary">Аудиодорожка отсутсвует</p>
    {% else %}
        <audio class="audio w-100" controls preload="auto">
            <source src="{{ audio_url }}"
                    type="audio/mp3">
        </audio>
    {% endif %}
</dev>
<script src="{% static 'js/set_audio_block.js' %}"></script>

scrum/mainapp/templates/mainapp/includes/inc__ban.html
{% load static %}

<div id="setban" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">
                    Установить БАН</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form action="{% url 'mainapp:set_user_ban_status' %}" method="post">
                {% csrf_token %}
                <input id="user_id" hidden="hidden" value="{{ author_user.pk }}" name="user_id">
                <div class="form-group col-md-10 mx-auto">
                    <div class="form-group">
                        <label for="reason" style="margin-top: 5px; margin-bottom: 5px;">
                            Укажите причину:
                        </label>
                        <p><select name="reason" required="required" id="reason">
                                <option>Недостойное поведение</option>
                                <option>Спам</option>
                                <option>Жестокость</option>
                                <option>Порнографический контент</option>
                                <option>Другое</option>
                            </select></p>
                        <label for="ban_description" style="margin-top: 5px; margin-bottom: 5px;">
                            Дополнительное описание:
                        </label>
                        <textarea name="ban_description" class="form-control" id="ban_description" rows="4" placeholder="Подробное описание (не обязательно)"></textarea>
                        <label for="ban_time" style="margin-top: 5px; margin-bottom: 5px;">
                            Время:
                        </label>
                        <p><select name="ban_time" required="required" id="ban_time">
                                <option>5 минут</option>
                                <option>30 минут</option>
                                <option>1 час</option>
                                <option>12 часов</option>
                                <option>1 сутки</option>
                                <option>7 дней</option>
                                <option>1 месяц</option>
                                <option>навсегда</option>
                            </select></p>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-outline-danger" id="ban">
                            Забанить
                        </button>
                        <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal">
                            Отмена
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



<form method="post" class="post_moderation_preview mx-auto rounded justify-content-center">
    <button type="button" class="btn btn-sm btn_archive mx-0" data-bs-toggle="modal" data-bs-target="#setban">
        Установить бан
    </button>
</form>


<!--<script src="{% static 'js/user_ban.js' %}"></script>-->

scrum/mainapp/templates/mainapp/includes/inc__search_comments_list.html
<div class="comment_list">
    {% for comment in comments %}
        <div class="search_comment_card shadow p-3 mb-5 bg-white rounded">
            <a href="{% url 'mainapp:read_post' comment.article.id %}"
               class="search_comment_heading">{{ comment.article.title }}</a>
            <div class="comment_info">
                <a href="#" class="comment_user">{{ comment.author_comment }}</a>
                <p class="comment_creation_data">{{ comment.updated_at }}</p>
            </div>
            <p class="search_comment_text">{{ comment.comment_text|safe }}</p>
            <a href="#" class="search_comment_button w-button shadow rounded">К коментарию</a>

            {#            {% include 'mainapp/includes/likes_comments_counter.html' %}#}

        </div>
    {% endfor %}
</div>

scrum/mainapp/templates/mainapp/includes/inc__search_in_menu.html
<form action="{% url 'main:search' %}" method="get">
    <input name="search_request" type="text" placeholder="Поиск">
    <button type="submit"><b>Отправить</b></button>
    menu
</form>

scrum/mainapp/templates/mainapp/includes/inc__search_in_result_page.html
{% load static %}

<div class="search_card shadow p-3 mb-2 bg-white rounded">
    <form action="javascript:handleSearch()"
          class="form-inline search-form">
        <input type="text" class="form-control search_request"
               name="search_request" id="search_request"
               placeholder="Введите запрос..."
               value="{% if search_request %}{{ search_request }}{% endif %}">
        <button type="submit"
                class="btn m-0 ms-3 search_button shadow rounded">Поиск
        </button>
    </form>
    <div class="search_filters" id="search_filters">
        <div class="menu-2 navbar" style="border-radius: 0 0 0.25rem 0.25rem;">
            <ul class="nav" style="min-width: 130px;">
                <li class="nav-item">
                    <a class="nav-link link-secondary text-center menu_btn m-0 {% if filter == 'posts' %} active shadow rounded {% endif %}"
                       id="posts" href="{% url 'main:search' %}">
                        Посты
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-secondary text-center menu_btn m-0 {% if filter == 'comments' %} active shadow rounded {% endif %}"
                       id="comments" href="{% url 'main:search' %}">
                        Комментарии
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-secondary text-center menu_btn m-0 {% if filter == 'users' %} active shadow rounded {% endif %}"
                       id="users" href="{% url 'main:search' %}">
                        Пользователи
                    </a>
                </li>
            </ul>
        </div>
{#        <div class="dropdown dropdown_sorting">#}
{#            <button class="btn btn-secondary dropdown-toggle btn-sm"#}
{#                    style="background-color: #60bef5; border-color: #60bef5; color: white;"#}
{#                    type="button"#}
{#                    id="dropdownMenuButton"#}
{#                    data-bs-toggle="dropdown" aria-expanded="false">#}
{#                &#8595; Дата публикации#}
{#            </button>#}
{#            {% if category %}#}
{#                <ul class="dropdown-menu"#}
{#                    aria-labelledby="dropdownMenuButton1">#}
{#                    {% for criteria, sorted_by in sorting_criteria.items %}#}
{#                        <a href="{% url 'main:category_sorted' category.slug sorted_by %}"#}
{#                           class="dropdown-item dropdown_sorting_item"#}
{#                           id="{{ sorted_by }}"#}
{#                           name="{{ criteria|safe }}">{{ criteria|safe }}</a>#}
{#                    {% endfor %}#}
{#                </ul>#}
{#            {% else %}#}
{#                <ul class="dropdown-menu"#}
{#                    aria-labelledby="dropdownMenuButton1">#}
{#                    {% for criteria, sorted_by in sorting_criteria.items %}#}
{#                        <a href="{% url 'main:index_sorted' sorted_by %}"#}
{#                           class="dropdown-item dropdown_sorting_item"#}
{#                           id="{{ sorted_by }}"#}
{#                           name="{{ criteria|safe }}">{{ criteria|safe }}</a>#}
{#                    {% endfor %}#}
{#                </ul>#}
{#            {% endif %}#}
{#        </div>#}
    </div>
</div>
<script src="{% static 'js/search_page.js' %}"></script>

scrum/mainapp/templates/mainapp/includes/inc__search_not_found.html
<h4 class="not_found text-center">
    {% if filter == 'posts' %}
        Посты
    {% elif filter == 'comments' %}
        Комментарии
    {% elif filter == 'users' %}
        Пользователи
    {% else %}
        Посты
    {% endif %}
    не найдены. Попробуйте уточнить поиск.
</h4>

scrum/mainapp/templates/mainapp/includes/inc__search_users_list.html
<div class="user_list">
    {% for user in users %}
        <div class="search_user_card shadow p-3 mb-5 bg-white rounded">
            <div class="user_info">
                <a href="#" class="search_user_heading">{{ user }}</a>
            </div>
            <a href="{% url 'mainapp:profile_page' user.id %}"
               class="search_user_button w-button shadow rounded">К профилю</a>

        </div>
    {% endfor %}
</div>

scrum/mainapp/templates/mainapp/includes/inc_menu.html
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/menu.css' %}">
{% endblock %}

<div class="d-flex menu w-100 justify-content-between m-auto mt-3 p-3 mb-5"
     style="max-width: max-content"></div>
<div style="height: 48px;"></div>


<div class="fixed-top d-flex menu bg-light w-100 justify-content-between m-auto mt-3 shadow p-3 mb-5 bg-white rounded"
     style="max-width: 960px">
    <div class="hubs">
        <ul class="nav flex-fill justify-content-start">
            <li class="nav-item p-2 {% if request.resolver_match.url_name == 'index' %} active shadow rounded {% endif %}">
                <a href="/"
                   class="nav-link p-1 link-secondary menu_btn">
                    Главная
                </a>
            </li>

            {% for category in categories %}
                <li class="nav-item p-2 {% if category.slug in request.path %} active shadow rounded {% endif %}">
                    <a class="nav-link p-1 text-capitalize link-secondary menu_btn"
                       href="{% url 'main:category' category.slug %}">
                        {{ category.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>


    {% if user.is_authenticated %}
    <div class="lk">
        <ul class="nav flex-fill justify-content-end">
        <style>
            .icon-badge-container {
                position: relative;
            }

            .icon-badge {
                background-color: red;
                font-size: 12px;
                color: white;
                text-align: center;
                width: 20px;
                height: 20px;
                border-radius: 35%;
                position: absolute;
                top: -5px;
                left: 18px;
            }
        </style>
        <li class="nav-item p-2">
            <div class="icon-badge-container" id = "search_press_auth">
                <a class="nav-link p-1 text-end link-dark menu_btn"
                   href="##">
                    <img src="{% static '/vendor/img_for_menu/search.png' %}"
                         alt="Поиск" width="20" height="20">
                </a>
            </div>
        </li>
        <li class="nav-item p-2">
            <div class="icon-badge-container">
                <a class="nav-link p-1 text-end link-secondary menu_btn"

                   href="{% url 'my_lk:my_alerts' %}">
                    <img src="{% static '/vendor/img_for_menu/bell.svg' %}"
                         alt="Оповещения" width="20" height="20">
                    {% if alert > 0 %}
                        <div class="icon-badge">{{ alert }}</div>
                    {% endif %}
                </a>
            </div>
        </li>
        <li class="nav-item p-2">
            <a class="nav-link p-1 text-end link-secondary menu_btn"
               href="{% url 'my_lk:my_profile' user.id %}">
                <img src="{% static '/vendor/img_for_menu/person-circle.svg' %}"
                     alt="Личный кабинет" width="20"
                     height="20"> {{ user.username }}
            </a>
        </li>
        <li class="nav-item p-2">
            <a class="nav-link p-1 text-end" href="{% url 'auth:logout' %}">
                <img src="{% static '/vendor/img_for_menu/door-closed-fill.svg' %}"
                     alt="Выйти" width="20"
                     height="20">
            </a>
        </li>
    {% else %}
        <div class="lk">
        <ul class="nav flex-fill justify-content-end">
            <li class="nav-item p-2">
                <div class="icon-badge-container" id = "search_press_notauth">
                    <a class="nav-link p-1 text-end link-dark menu_btn"
                       href="##">
                        <img src="{% static '/vendor/img_for_menu/search.png' %}"
                             alt="Поиск" width="20" height="20">
                    </a>
                </div>
            </li>
            <li class="nav-item p-2 align-middle">
                <a class="nav-link p-1 text-end" href="{% url 'auth:login' %}">
                    <img src="{% static '/vendor/img_for_menu/door-open.svg' %}"
                         alt="Войти" width="20"
                         height="20">
                </a>
            </li>
            <li class="nav-item p-2 align-middle">
                <a class="nav-link p-1 text-end"
                   href="{% url 'auth:register' %}">
                    <img src="{% static '/vendor/img_for_menu/person-plus.svg' %}"
                         alt="Регистрация" width="20"
                         height="20">
                </a>
            </li>
        </ul>
    {% endif %}
    </div>
    </div>

    <div id = "hide_search" style="display: none">
    <div class="fixed-top d-flex menu bg-light w-200 justify-content-between m-auto mt-3 shadow p-3 mb-5 bg-white rounded"
    style="max-width: 370px; top: 72px; left: 590px;">    
        <div>            
            <input type="text" size="40" id = "search_line_text">
            <a class="link-dark menu_btn" id = "press_search_start" href="##"><img src="{% static '/vendor/img_for_menu/search.png' %}" alt="Поиск" width="20" height="20"></a>
            <a class="link-dark menu_btn" id = "press_search_cancel" href="##"><img src="{% static '/vendor/img_for_menu/cancel_search.png' %}" alt="Поиск" width="20" height="20"></a>
        </div>
    </div>
</div>


</div>

{% block javascript %}
<script>
    $("#press_search_cancel").click(function () {
        $('#hide_search')[0].style.removeProperty("display: table-row;");
        $('#hide_search')[0].style.setProperty("display", "none");       
    });

    var elems = $("[id^='search_press']")
    elems.on("click", function () {
        console.log ($('#hide_search')[0].style.display)
        if ($('#hide_search')[0].style.display == 'none')
        {
            $('#hide_search')[0].style.removeProperty("display: none");
            $('#hide_search')[0].style.setProperty("display", "table-row");         
        }
        else{
            $('#hide_search')[0].style.removeProperty("display: table-row;");
            $('#hide_search')[0].style.setProperty("display", "none");              
        }
    });      
    
    $('#search_line_text').keypress(function (e) {
        if (event.key === "Enter") {
            var value = document.getElementById('search_line_text').value
            var url = '/search/?search_request=' + value
            window.location.href = url;       
        }
    });      

    $(document).keyup(function(e) {
        if (e.key === "Escape") { // escape key maps to keycode `27`
            $('#hide_search')[0].style.removeProperty("display: table-row;");
            $('#hide_search')[0].style.setProperty("display", "none");     
       }
   });    
      
    $('#press_search_start').click(function () {
        var value = document.getElementById('search_line_text').value
        var url = '/search/?search_request=' + value
        window.location.href = url;       
    });    

</script>
{% endblock javascript %}

scrum/mainapp/templates/mainapp/includes/raiting_of_post.html
{% load static %}

<div class="d-flex mx-2">
    <div>
        <img src="{% static 'vendor/img/bar-chart-fill.svg' %}" alt="Рейтинг" width="20" height="20"
            title="Рейтинг поста">
    </div>
    <div class="mx-1" id='id_rating_count'>
        {{ post.rating}}
    </div>
</div>