scrum/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
    # path("", adminapp.index, name="index"),
    path("users/", adminapp.get_users, name="get_users"),
    path("users/delete/<int:pk>/", adminapp.change_user_status,
         name="change_user_status"),
    path("users/role/<int:pk>/<str:role>/", adminapp.change_user_role,
         name="change_user_role"),
    path("users/create/", adminapp.create_user, name="create_user"),
    path("users/get/<int:pk>/", adminapp.get_user_info, name="get_user"),
    # path("categories/", adminapp.get_categories, name="get_categories"),
    # path("posts/", adminapp.get_posts, name="get_posts"),
    path("search/", adminapp.search_ajax, name="search_ajax"),
]

scrum/lkapp/urls.py
from django.urls import path

import lkapp.views as lkapp

app_name = "lkapp"

urlpatterns = [
    # Профиль
    path("profile/<int:pk>/", lkapp.my_profile, name="my_profile"),
    path("profile/<int:pk>/update", lkapp.profile_update, name="profile_update"),
    path("profile/<int:pk>/delete", lkapp.delete_user, name="delete_user"),
    path("profile/<int:pk>/set_email_settings", lkapp.set_mail_settting_switcher, name="switch_email_settings"),
    # Ajax-mail_checked
    path("profile/<int:pk>/switch_email_settings_ajax", lkapp.set_mail_settting_switcher,
         name="switch_email_settings_ajax"),
    # Статьи/Черновики
    path("post/create/", lkapp.post_creation, name="post_creation"),
    path("myposts/", lkapp.my_posts, name="my_posts"),
    path("myposts/published", lkapp.my_posts_ajax, name="published"),
    path("myposts/moderation", lkapp.my_posts_ajax, name="moderation"),
    path("myposts/correction", lkapp.my_posts_ajax, name="correction"),
    path("myposts/archive", lkapp.my_posts_ajax, name="archive"),
    path("myposts/myposts", lkapp.my_posts_ajax, name="myposts_ajax"),
    path("draft/", lkapp.my_drafts, name="drafts"),
    path("draft/<int:pk>/", lkapp.preview_draft, name="read_draft"),
    path("draft/<int:pk>/moderation", lkapp.publicating_post,
         name="go_on_moderation_post"),
    path("draft/<int:pk>/delete", lkapp.delete_drafts, name="delete_drafts"),
    path("myposts/<int:pk>/", lkapp.preview_post, name="preview_post"),
    path("myposts/<int:pk>/publicate",
         lkapp.publicating_post, name="publicate_post"),
    path("myposts/<int:pk>/deactivate",
         lkapp.archivating_post, name="deactivate_post"),
    path("posts_moderation/", lkapp.posts_on_moderation,
         name="posts_for_moderation"),
    path("post_moderation/<int:pk>/",
         lkapp.post_moderation, name="post_moderation"),
    path(
        "post_moderation/<int:pk>/correction/",
        lkapp.set_article_status_correction,
        name="set_article_status_correction",
    ),
    path(
        "post_moderation/<int:pk>/published/", lkapp.set_article_status_published, name="set_article_status_published"
    ),
    path("myposts/<int:pk>/edit", lkapp.edit_post, name="edit_post"),
    path("draft/<int:pk>/edit", lkapp.edit_draft, name="edit_draft"),

    # Уведомления
    path("my_alerts/", lkapp.my_alerts, name="my_alerts"),
    path("my_alerts/comment_alerts", lkapp.my_alerts, name="comment_alerts"),
    path("my_alerts/grade_alerts", lkapp.my_alerts, name="grade_alerts"),
    path("my_alerts/moder_alerts", lkapp.my_alerts, name="moder_alerts"),
    path("my_alerts/subscribe_alerts", lkapp.my_alerts, name="subscribe_alerts"),
    # Кнопки уведомлений

    # ajax меню блока Alerts++
    path("my_alerts/my_alerts_ajax", lkapp.my_alerts_ajax, name="my_alerts_ajax"),
    path("my_alerts/comment_alerts_ajax",
         lkapp.my_alerts_ajax, name="comment_alerts_ajax"),
    path("my_alerts/grade_alerts_ajax",
         lkapp.my_alerts_ajax, name="grade_alerts_ajax"),
    path("my_alerts/moder_alerts_ajax",
         lkapp.my_alerts_ajax, name="moder_alerts_ajax"),
    path("my_alerts/subscribe_alerts_ajax",
         lkapp.my_alerts_ajax, name="subscribe_alerts_ajax"),
    # ajax меню блока Alerts--

    path("delete_all_alerts/", lkapp.delete_all_alerts, name="delete_all_alerts"),
    path("delete_read_alerts/", lkapp.delete_read_alerts,
         name="delete_read_alerts"),
    path("delete_alert/<int:pk>/", lkapp.delete_alert, name="delete_alert"),
    path("mark_as_read/<int:pk>/", lkapp.mark_as_read, name="mark_as_read"),

    # Жалобы
    path("complains/", lkapp.my_complains, name="my_complains"),
    path("complains/complains", lkapp.my_complains_ajax, name="my_complains_ajax"),
    path("complains/complain_posts", lkapp.my_complains_post_ajax, name="my_complains_post_ajax"),
    path("complains/complain_comments", lkapp.my_complains_comments_ajax, name="my_complains_comments_ajax"),
    path("complains/moderation/<int:pk>/", lkapp.complain_moderation, name="complain_moderation"),
    path("complains/moderation/<int:pk>/denied/", lkapp.set_complain_status_denied,
         name="set_complain_status_denied"),
    path("complains/moderation/<int:pk>/approve/", lkapp.set_complain_status_approve,
         name="set_complain_status_approve"),
    # Подписки
    path("mysubscribes/", lkapp.my_subscribes, name="my_subscribes"),
]

scrum/mainapp/urls.py
from django.urls import path

from .views import (
    main,
    read_post,
    hubs,
    like_post,
    dislike_post,
    comments_count,
    allert_counter,
    profile_page,
    follow,
    like_author,
    dislike_author,
    post_complaint,
    comment_complaint,
    search, get_audio_name, get_audio_block,
    set_user_ban_status,
    set_user_unban_status, like_comment, dislike_comment, comment_ajax,like_dislike_comment_ajax, regenerate_audio
)

app_name = "mainapp"

urlpatterns = [
    # Страница автора
    path("user/<int:pk>", profile_page, name="profile_page"),

    # Оценка автора
    path("user/like/<int:pk>", like_author, name="like_author"),
    path("user/dislike/<int:pk>", dislike_author, name="dislike_author"),

    # Оценка автора (ajax)
    path("user/like/<int:pk>/like_user_count",
         like_author, name="like_author_ajax"),
    path("user/dislike/<int:pk>/dislike_user_count",
         dislike_author, name="dislike_author_ajax"),

    # Подписка
    path("user/follow/<int:pk>", follow, name="follow"),

    # Главная + страницы Хабов + сортировка
    path("", main, name="index"),
    path("index/<str:sorted_by>/", main, name="index_sorted"),
    path("category/<slug:slug>/", hubs, name="category"),
    path("index/<slug:slug>/<str:sorted_by>/", hubs, name="category_sorted"),

    # Страница статьи
    path("post/<int:pk>/", read_post, name="read_post"),

    # Оценка статьи
    path("post/<int:pk>/like_count", like_post, name="like_count"),
    path("post/<int:pk>/dislike_count", dislike_post, name="dislike_count"),

    # Комментарии
    path("post/<int:pk>/comments_count", comments_count, name="comments_count"),
    path("post/<int:pk>/get_comment", comment_ajax, name="get_comment"),
    path("post/<int:pk>/like_dislike_comment", like_dislike_comment_ajax, name="like_dislike_comment"),    

    # Жалоба на комментарий
    path("post/<int:pk>/comment_complaint",
         comment_complaint, name="comment_complaint"),

    # Оценка комментария
    path("post/<int:pk>/like_comment", like_comment, name="like_comment"),
    path("post/<int:pk>/dislike_comment", dislike_comment, name="dislike_comment"),


    # Счетчик уведомлений
    path("post/allert_counter", allert_counter, name="allert_counter"),

    # Поиск
    path("post/<int:pk>/post_complaint", post_complaint, name="post_complaint"),
    path("search/", search, name="search"),

    # Аудио
    path("media/article_audio/<str:audio_name>/", get_audio_name, name="get_audio_name"),
    path("post/get_audio_block/", get_audio_block, name="get_audio_block"),
    path("post/regenerate_audio/", regenerate_audio, name="regenerate_audio"),
    
    # Бан
    path("user/ban/", set_user_ban_status,
         name="set_user_ban_status"),
    path("user/<int:pk>/unban/", set_user_unban_status,
         name="set_user_unban_status"),
]

scrum/scrum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('my_admin/', include('adminapp.urls', namespace='my_admin')),
    path('my_lk/', include('lkapp.urls', namespace='my_lk')),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

scrum/lkapp/models.py
from django.db import models

from authapp.models import User
from mainapp.models import Article


class Alert(models.Model):
    """Модель содержащая данные по уведомлениям"""

    alert_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="alert_user")
    action_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="action_user")

    class EventType(models.TextChoices):
        comment = "comment"
        answer = "answer"
        post_like = "post_like"
        post_dislike = "post_dislike"
        new_post_sub = "new_post_sub"
        comment_like = "comment_like"
        comment_dislike = "comment_dislike"
        answer_like = "answer_like"
        answer_dislike = "answer_dislike"
        author_like = "author_like"
        author_dislike = "author_dislike"
        approve_status = "approve_status"
        reject_status = "reject_status"
        another_status = "another_status"
        author_subscribe = "author_subscribe"
        author_unsubscribe = "author_unsubscribe"
        approve_complaint_post_sub = "approve_complaint_post_sub"
        approve_complaint_post_bu = "approve_complaint_post_bu"
        reject_complaint_post = "reject_complaint_post"
        approve_complaint_comment_sub = "approve_complaint_comment_sub"
        approve_complaint_comment_bu = "approve_complaint_comment_bu"
        reject_complaint_comment = "complaint_comment"
        user_ban = "user_ban"

    event_type = models.CharField(
        max_length=32,
        choices=EventType.choices,
        verbose_name="Тип события",
    )

    parent_obj = models.IntegerField(verbose_name="id объекта", null=True)
    not_read = models.BooleanField(verbose_name="Не прочитано", blank=False, null=False, default=True)
    created_at = models.DateTimeField(verbose_name="Создано", editable=False, auto_now_add=True)

    class Meta:
        verbose_name = "Оповещения"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.event_type, self.alert_user


class UserSettings(models.Model):
    """Модель содержащая настройки пользователя"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="users_settings")
    email_alerts_is_on = models.BooleanField(verbose_name="уведомления на почту", blank=False, null=False, default=True)
    lk_alerts_is_on = models.BooleanField(verbose_name="уведомления в лк", blank=False, null=False, default=True)

    class Meta:
        verbose_name = "Настройки"
        verbose_name_plural = verbose_name


class UserSettingsLog(models.Model):
    """Модель содержащая лог изменений настроек пользователя"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="users_log")

    switched_setting = models.TextField(verbose_name="описание", max_length=64, blank=False, null=False)
    created_at = models.DateTimeField(verbose_name="изменено", editable=False, auto_now_add=True)

    class Meta:
        verbose_name = "Лог изменений"
        verbose_name_plural = verbose_name

    def __str__(self):
        return f'{self.user} change {self.switched_setting}'

scrum/lkapp/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from django.forms import ModelForm

from authapp.models import User
from mainapp.models import Article


class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", 'sex', 'age', "email", "avatar", "about_me"]
        # field_order = ["age", "name"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields["username"].help_text = None


class PostCreationForm(ModelForm):
    body = forms.CharField(
        label="Текст статьи",
        widget=CKEditorUploadingWidget(config_name="article"),
    )

    class Meta:
        model = Article
        fields = ('title',
                  'preview',
                  'body',
                  'image',
                  'category',
                  'tag')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs = {"rows": 1}
        self.fields["tag"].widget.attrs = {"rows": 1}
        self.fields["preview"].widget.attrs = {"rows": 4}
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

scrum/lkapp/templates/lkapp/includes/alert_list.html
{% load static %}

<!-- Блок со статьями -->
{% for alert in alerts %}
{% if alert.not_read == True %}
<div class="table_alerts table-responsive shadow rounded p-1 mb-3">
    {% else %}
    <div class="table-responsive p-1 mb-3">
        {% endif %}
        <table class="table table-borderless mb-0" style="font-size: 12px;">
            {% if alert.not_read == True %}
            <tr style="font-weight: bold;">
                {% else %}
            <tr>
                {% endif %}
                <td class="d-flex align-items-center">
                    <a href="{% url 'my_lk:comment_alerts' %}">
                        <img src="{% static alert.icon %}" alt="Иконка" width="20" height="20">
                    </a>
                    <p class="mb-0 mx-3">{{ alert.created_at }}</p>
                </td>
                <td class="d-flex align-items-center">
                    <a class="nav-link link-dark" href="##" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                        {% if alert.event_type == 'author_like' or alert.event_type == 'author_dislike' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">{{ alert.system_text }}
                            {% if alert.event_type == 'author_like' %}
                            <b class="h6 text-success">{{ alert.username }}</b>
                            {% else %}
                            <b class="h6 text-danger">{{ alert.username }}</b>
                            {% endif %}
                        </p>
                        {% endif %}
                        {% if alert.event_type == 'post_like' or alert.event_type == 'post_dislike' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {% if alert.event_type == 'post_like' %}
                            <b class="h6 text-success">{{ alert.username }}</b>
                            {% else %}
                            <b class="h6 text-danger">{{ alert.username }}</b>
                            {% endif %}
                            {{ alert.system_text }}
                        </p>
                        {% endif %}
                        {% if alert.event_type == 'comment' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {{ alert.system_text }}
                            <b class="h6 text-success">{{ alert.username }}</b>
                        </p>
                        {{ alert.comment|safe }}
                        {% endif %}
                        {% if alert.event_type == 'approve_status' or alert.event_type == 'reject_status' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">{{ alert.system_text }}</p>
                        {% endif %}
                        {% if alert.event_type == 'author_unsubscribe' or alert.event_type == 'author_subscribe' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {{ alert.system_text }}
                            {% if alert.event_type == 'author_subscribe' %}
                            <b class="h6 text-success">{{ alert.username }}</b>
                            {% else %}
                            <b class="h6 text-danger">{{ alert.username }}</b>
                            {% endif %}
                        </p>
                        {% endif %}
                        {% if alert.event_type == 'approve_complaint_post_sub' or alert.event_type == 'reject_complaint_post' or alert.event_type == 'approve_complaint_post_bu'%}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {{ alert.system_text }}
                        </p>
                        <p style="font-weight: normal" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {{ alert.comment }}
                        </p>
                        {% endif %}
                        {% if alert.event_type == 'approve_complaint_comment_sub' or alert.event_type == 'reject_complaint_comment' or alert.event_type == 'approve_complaint_comment_bu'%}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {{ alert.system_text|safe }}
                        </p>
                        <p style="font-weight: normal" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            {{ alert.comment|safe }}
                        </p>
                        {% endif %}
                        {% if alert.event_type == 'new_post_sub' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            <b class="h6 text-success">{{ alert.username }}</b>
                            {{ alert.system_text }}
                        </p>
                        {% endif %}
                        {% if alert.event_type == 'user_ban' %}
                        <p class="m-0 mx-1" name = "{{ alert.parent_url }}#{{ alert.parent_obj }}" id = "redirect" name_read ="{% url 'my_lk:mark_as_read' alert.id %}">
                            <b class="h6 text-danger">{{ alert.username }}</b>
                            {{ alert.system_text }}
                        </p>
                        <p style="font-weight: normal">
                            {{ alert.reason }}
                        </p>
                        {% endif %}
                    </a>
                </td>
                <td class="btns d-flex justify-content-between align-items-center">
                    {% if alert.not_read == True %}
                    <a class="btn btn-sm btn-outline-secondary btn_blue text-center" role="button"
                        href="##" id = "alert_read" name ="{% url 'my_lk:mark_as_read' alert.id %}">
                        <div class="btns_hover">
                            <p class="m-0" name ="{% url 'my_lk:mark_as_read' alert.id %}" id = 'read_alert'>Прочитать</p>
                        </div>
                    </a>
                    {% endif %}
                    <a class="btn btn-sm btn_archive text-center" role="button"
                        href="##">
                        <div class="btns_hover">
                            <p class="m-0" name = "{% url 'my_lk:delete_alert' alert.id %}" id = 'del_alert'>Стереть</p>
                        </div>
                    </a>
                </td>
            </tr>
        </table>
    </div>
    {% endfor %}
</div>

scrum/lkapp/templates/lkapp/includes/btns_for_posts.html
{% load static %}

<div class="btns_drafts d-flex justify-content-between m-2 mb-0">
    <div class="positive_btns">
        {% if article.status == "correction" or article.status == "published" %}
        <a href="{% url 'my_lk:edit_post' article.id %}" class="{% if ban %} disabled {% endif %} btn btn-sm btn_blue text-center shadow" role="button">
            <div class="btns_hover">
                <p class="m-0">Редактировать</p>
            </div>
        </a>
        {% endif %}
        <a href="{% url 'my_lk:preview_post' article.id %}" class="btn btn-sm btn_blue text-center shadow" role="button">
            <div class="btns_hover">
                <p class="m-0">Предпросмотр</p>
            </div>
        </a>
    </div>
    <div class="negative_btns">
        {% if article.status == "published" %}
        <a href="{% url 'my_lk:deactivate_post' article.id %}" class="btn btn-sm btn-outline-danger btn_archive text-center shadow" role="button">
            <div class="btns_hover">
                <p class="m-0">В архив</p>
            </div>
        </a>
        {% endif %}
    </div>
</div>

scrum/lkapp/templates/lkapp/includes/complain_list.html
{% load static %} {% for complain in complains %}
<div style="word-break: break-word" class="d-flex flex-column table_post shadow rounded mb-3 p-2 table-responsive">
    <!-- Таблица -->
    <table class="table table-borderless mb-0" style="font-size: 12px">
        <tr>
            <td class="d-flex align-items-center justify-content-between" style="font-weight: bold">
                <div class="d-flex flex-wrap">
                    {% if complain.comment is None %}
                    <img class="me-3" src="{% static 'vendor/img_for_alerts/file-post.svg' %}" alt="Иконка" width="23"
                         height="23"/>
                    {% else %}
                    <img class="me-3" src="{% static 'vendor/img_for_alerts/chat-left-text-fill.svg' %}" alt="Иконка" width="23"
                         height="23"/>
                    {% endif %}
                    <p class="me-2">{{ complain.created_at }}</p>
                    <p class="m-0" style="font-weight: bold">
                        {{ article.author.username }}
                    </p>
                </div>
                <div class="d-flex flex-wrap">
                    <p class="text-capitalize">{{ complain.submitted_user }}</p>
                </div>
            </td>
            <td class="d-flex flex-column flex-wrap mb-2">
                {% if complain.comment is None %}
                <a class="nav-link p-0 link-dark" href="{% url 'mainapp:read_post' complain.article.id %}">
                    <h5>Жалоба на статью - {{ complain.article.title }}</h5>
                </a>
                {% else %}
                <h5>Жалоба на комментарий к статье - {{ complain.comment.article.title}}</h5>
                {% endif %}
            </td>
        </tr>
    </table>

    <div class="btns_drafts d-flex justify-content-between m-1">
        <div class="positive_btns">
            <a href="{% url 'my_lk:complain_moderation' complain.id %}"
               class="btn btn-sm btn_blue text-center" role="button">
                Проверить
            </a>
        </div>
    </div>
</div>
{% endfor %}

scrum/lkapp/templates/lkapp/includes/filters_complains.html
<div class="menu_3_lvl bg-secondary shadow rounded p-3 mt-5 mb-5">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link link-light menu_filters complains
            {% if 'complains' in request.path %} active_filters shadow rounded {% endif %}"
            href="##" id = 'filtercomplain' name = 'complains'>Все</a>
        </li>
        <li class="nav-item">
            <a class="nav-link link-light menu_filters complain_posts
            {% if request.resolver_match.url_name == 'complain_posts' %} active_filters shadow rounded {% endif %}"
            href="##" id = 'filtercomplain' name = 'complain_posts' >Посты</a>
        </li>
        <li class="nav-item">
            <a class="nav-link link-light menu_filters complains_comments
            {% if request.resolver_match.url_name == 'complains_comments' %} active_filters shadow rounded {% endif %}"
            href="##" id = 'filtercomplain' name = 'complains_comments'>Комментарии</a>
        </li>
    </ul>
</div>

scrum/lkapp/templates/lkapp/includes/inc__lk_menu.html
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'style/menu.css' %}">
{% endblock %}

<div class="container-2 rounded bg-light shadow w-container"
    style="margin-left: auto; margin-right: auto; max-width: 960px;">
    <header class="header_lk navbar flex-column navbar-dark" style="
    border-radius: 0.25rem 0.25rem 0 0;
">
        <div class="avatar m-auto d-flex flex-column justify-content-center" style="max-width: 200px;">
            {% if not user.avatar %}
            <img class="shadow mw-100 rounded-circle m-auto" src="{% static 'vendor/profile_avatar/default.jpg' %}"
                 alt="Avatar">
            {% endif %}
            {% if user.avatar %}
            <img class="shadow mw-100 rounded-circle m-auto" src="{{ media_url }}{{ user.avatar }}" alt="Avatar">
            {% endif %}
        </div>
        <a class="nav-link link-light my-1 mx-auto menu_welcome" href="{% url 'my_lk:my_profile' user.id %}">Добро пожаловать,
            {{ user.username }}</a>

    </header>
    <div class="menu-2 navbar p-3" style="border-radius: 0 0 0.25rem 0.25rem;">
        <ul class="nav" style="min-width: 130px;">
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if request.resolver_match.url_name == 'my_profile' %} active shadow rounded {% endif %}"
                   href="{% url 'my_lk:my_profile' user.id %}">Профиль </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if request.resolver_match.url_name == 'drafts' %} active shadow rounded {% endif %}"
                   href="{% url 'my_lk:drafts' %}">Черновики</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if 'myposts' in request.path %} active shadow rounded {% endif %}"
                   href="{% url 'my_lk:my_posts' %}">Мои статьи</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if 'mysubscribes' in request.path %} active shadow rounded {% endif %}"
                    href="{% url 'my_lk:my_subscribes' %}">Подписки</a>
            </li>

            <!-- Если пользователь с ролью модератор -->
            {% if user.user_role == "moderator" or user.user_role == "administrator" %}
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if request.resolver_match.url_name == 'posts_for_moderation' %} active shadow rounded {% endif %}"
                   href="{% url 'my_lk:posts_for_moderation' %}">Модерация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if request.resolver_match.url_name == 'my_complains' %} active shadow rounded {% endif %}"
                   href="{% url 'my_lk:my_complains' %}">Жалобы</a>
            </li>
            {% endif %}
            <!-- Если пользователь с ролью администратор -->
            {% if user.user_role == "administrator" %}
            <li class="nav-item">
                <a class="nav-link link-secondary text-center menu_btn {% if request.resolver_match.url_name == 'profile_update' %} active shadow rounded {% endif %}"
                   href="{% url 'my_admin:get_users' %}">Админка</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>