scrum/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
    # path("", adminapp.index, name="index"),
    path("users/", adminapp.get_users, name="get_users"),
    path("users/delete/<int:pk>/", adminapp.change_user_status,
         name="change_user_status"),
    path("users/role/<int:pk>/<str:role>/", adminapp.change_user_role,
         name="change_user_role"),
    path("users/create/", adminapp.create_user, name="create_user"),
    path("users/get/<int:pk>/", adminapp.get_user_info, name="get_user"),
    # path("categories/", adminapp.get_categories, name="get_categories"),
    # path("posts/", adminapp.get_posts, name="get_posts"),
    path("search/", adminapp.search_ajax, name="search_ajax"),
]

scrum/lkapp/urls.py
from django.urls import path

import lkapp.views as lkapp

app_name = "lkapp"

urlpatterns = [
    # Профиль
    path("profile/<int:pk>/", lkapp.my_profile, name="my_profile"),
    path("profile/<int:pk>/update", lkapp.profile_update, name="profile_update"),
    path("profile/<int:pk>/delete", lkapp.delete_user, name="delete_user"),
    path("profile/<int:pk>/set_email_settings", lkapp.set_mail_settting_switcher, name="switch_email_settings"),
    # Ajax-mail_checked
    path("profile/<int:pk>/switch_email_settings_ajax", lkapp.set_mail_settting_switcher,
         name="switch_email_settings_ajax"),
    # Статьи/Черновики
    path("post/create/", lkapp.post_creation, name="post_creation"),
    path("myposts/", lkapp.my_posts, name="my_posts"),
    path("myposts/published", lkapp.my_posts_ajax, name="published"),
    path("myposts/moderation", lkapp.my_posts_ajax, name="moderation"),
    path("myposts/correction", lkapp.my_posts_ajax, name="correction"),
    path("myposts/archive", lkapp.my_posts_ajax, name="archive"),
    path("myposts/myposts", lkapp.my_posts_ajax, name="myposts_ajax"),
    path("draft/", lkapp.my_drafts, name="drafts"),
    path("draft/<int:pk>/", lkapp.preview_draft, name="read_draft"),
    path("draft/<int:pk>/moderation", lkapp.publicating_post,
         name="go_on_moderation_post"),
    path("draft/<int:pk>/delete", lkapp.delete_drafts, name="delete_drafts"),
    path("myposts/<int:pk>/", lkapp.preview_post, name="preview_post"),
    path("myposts/<int:pk>/publicate",
         lkapp.publicating_post, name="publicate_post"),
    path("myposts/<int:pk>/deactivate",
         lkapp.archivating_post, name="deactivate_post"),
    path("posts_moderation/", lkapp.posts_on_moderation,
         name="posts_for_moderation"),
    path("post_moderation/<int:pk>/",
         lkapp.post_moderation, name="post_moderation"),
    path(
        "post_moderation/<int:pk>/correction/",
        lkapp.set_article_status_correction,
        name="set_article_status_correction",
    ),
    path(
        "post_moderation/<int:pk>/published/", lkapp.set_article_status_published, name="set_article_status_published"
    ),
    path("myposts/<int:pk>/edit", lkapp.edit_post, name="edit_post"),
    path("draft/<int:pk>/edit", lkapp.edit_draft, name="edit_draft"),

    # Уведомления
    path("my_alerts/", lkapp.my_alerts, name="my_alerts"),
    path("my_alerts/comment_alerts", lkapp.my_alerts, name="comment_alerts"),
    path("my_alerts/grade_alerts", lkapp.my_alerts, name="grade_alerts"),
    path("my_alerts/moder_alerts", lkapp.my_alerts, name="moder_alerts"),
    path("my_alerts/subscribe_alerts", lkapp.my_alerts, name="subscribe_alerts"),
    # Кнопки уведомлений

    # ajax меню блока Alerts++
    path("my_alerts/my_alerts_ajax", lkapp.my_alerts_ajax, name="my_alerts_ajax"),
    path("my_alerts/comment_alerts_ajax",
         lkapp.my_alerts_ajax, name="comment_alerts_ajax"),
    path("my_alerts/grade_alerts_ajax",
         lkapp.my_alerts_ajax, name="grade_alerts_ajax"),
    path("my_alerts/moder_alerts_ajax",
         lkapp.my_alerts_ajax, name="moder_alerts_ajax"),
    path("my_alerts/subscribe_alerts_ajax",
         lkapp.my_alerts_ajax, name="subscribe_alerts_ajax"),
    # ajax меню блока Alerts--

    path("delete_all_alerts/", lkapp.delete_all_alerts, name="delete_all_alerts"),
    path("delete_read_alerts/", lkapp.delete_read_alerts,
         name="delete_read_alerts"),
    path("delete_alert/<int:pk>/", lkapp.delete_alert, name="delete_alert"),
    path("mark_as_read/<int:pk>/", lkapp.mark_as_read, name="mark_as_read"),

    # Жалобы
    path("complains/", lkapp.my_complains, name="my_complains"),
    path("complains/complains", lkapp.my_complains_ajax, name="my_complains_ajax"),
    path("complains/complain_posts", lkapp.my_complains_post_ajax, name="my_complains_post_ajax"),
    path("complains/complain_comments", lkapp.my_complains_comments_ajax, name="my_complains_comments_ajax"),
    path("complains/moderation/<int:pk>/", lkapp.complain_moderation, name="complain_moderation"),
    path("complains/moderation/<int:pk>/denied/", lkapp.set_complain_status_denied,
         name="set_complain_status_denied"),
    path("complains/moderation/<int:pk>/approve/", lkapp.set_complain_status_approve,
         name="set_complain_status_approve"),
    # Подписки
    path("mysubscribes/", lkapp.my_subscribes, name="my_subscribes"),
]

scrum/mainapp/urls.py
from django.urls import path

from .views import (
    main,
    read_post,
    hubs,
    like_post,
    dislike_post,
    comments_count,
    allert_counter,
    profile_page,
    follow,
    like_author,
    dislike_author,
    post_complaint,
    comment_complaint,
    search, get_audio_name, get_audio_block,
    set_user_ban_status,
    set_user_unban_status, like_comment, dislike_comment, comment_ajax,like_dislike_comment_ajax, regenerate_audio
)

app_name = "mainapp"

urlpatterns = [
    # Страница автора
    path("user/<int:pk>", profile_page, name="profile_page"),

    # Оценка автора
    path("user/like/<int:pk>", like_author, name="like_author"),
    path("user/dislike/<int:pk>", dislike_author, name="dislike_author"),

    # Оценка автора (ajax)
    path("user/like/<int:pk>/like_user_count",
         like_author, name="like_author_ajax"),
    path("user/dislike/<int:pk>/dislike_user_count",
         dislike_author, name="dislike_author_ajax"),

    # Подписка
    path("user/follow/<int:pk>", follow, name="follow"),

    # Главная + страницы Хабов + сортировка
    path("", main, name="index"),
    path("index/<str:sorted_by>/", main, name="index_sorted"),
    path("category/<slug:slug>/", hubs, name="category"),
    path("index/<slug:slug>/<str:sorted_by>/", hubs, name="category_sorted"),

    # Страница статьи
    path("post/<int:pk>/", read_post, name="read_post"),

    # Оценка статьи
    path("post/<int:pk>/like_count", like_post, name="like_count"),
    path("post/<int:pk>/dislike_count", dislike_post, name="dislike_count"),

    # Комментарии
    path("post/<int:pk>/comments_count", comments_count, name="comments_count"),
    path("post/<int:pk>/get_comment", comment_ajax, name="get_comment"),
    path("post/<int:pk>/like_dislike_comment", like_dislike_comment_ajax, name="like_dislike_comment"),    

    # Жалоба на комментарий
    path("post/<int:pk>/comment_complaint",
         comment_complaint, name="comment_complaint"),

    # Оценка комментария
    path("post/<int:pk>/like_comment", like_comment, name="like_comment"),
    path("post/<int:pk>/dislike_comment", dislike_comment, name="dislike_comment"),


    # Счетчик уведомлений
    path("post/allert_counter", allert_counter, name="allert_counter"),

    # Поиск
    path("post/<int:pk>/post_complaint", post_complaint, name="post_complaint"),
    path("search/", search, name="search"),

    # Аудио
    path("media/article_audio/<str:audio_name>/", get_audio_name, name="get_audio_name"),
    path("post/get_audio_block/", get_audio_block, name="get_audio_block"),
    path("post/regenerate_audio/", regenerate_audio, name="regenerate_audio"),
    
    # Бан
    path("user/ban/", set_user_ban_status,
         name="set_user_ban_status"),
    path("user/<int:pk>/unban/", set_user_unban_status,
         name="set_user_unban_status"),
]

scrum/scrum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('my_admin/', include('adminapp.urls', namespace='my_admin')),
    path('my_lk/', include('lkapp.urls', namespace='my_lk')),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

scrum/adminapp/models.py
# Create your models here.

scrum/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import TextInput, EmailInput

from authapp.models import User


class AdminUserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username', 'password1', 'password2', 'email', 'first_name',
            'last_name', 'user_role'
        )

        widgets = {
            'username': TextInput(attrs={'placeholder': 'user123'}),
            'email': EmailInput(attrs={'placeholder': 'example@domain.com'}),
            'first_name': TextInput(attrs={'placeholder': 'Иван'}),
            'last_name': TextInput(attrs={'placeholder': 'Иванов'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Имя пользователя"
        self.fields['password1'].label = "Пароль"
        self.fields['password2'].label = "Введите пароль еще раз"
        self.fields['email'].label = "Почтовый адрес"
        self.fields['first_name'].label = "Имя"
        self.fields['last_name'].label = "Фамилия"
        self.fields['user_role'].label = "Роль"
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''

scrum/adminapp/views.py
from django.conf import settings
from tzlocal import get_localzone
import pytz
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from adminapp.forms import AdminUserRegisterForm
from adminapp.helpers.search import perform_search_ajax
from authapp.models import User
from mainapp.helpers import get_current_user
from mainapp.helpers.article.article import get_category_list
from mainapp.helpers.search import perform_search


@login_required
def get_users(request):
    timezone.activate(pytz.timezone(str(get_localzone())))
    current_user = get_current_user(request)
    if current_user.user_role == "administrator":
        title = "Админка|Пользователи"
        content = {
            "title": title,
            'users': User.objects.all().order_by('pk'),
            "current_user": current_user,
        }
        return render(request, "adminapp/users_table_page.html", content)
    return HttpResponseRedirect(reverse("main:index"))


@login_required
def change_user_status(request, pk):
    current_user = get_current_user(request)
    if current_user.user_role == "administrator":
        user = User.objects.filter(pk=pk).first()
        if not (
                user.is_superuser or current_user.id == user.id or user.user_role == 'administrator' and not current_user.is_superuser):
            user.is_active = not user.is_active
        user.save()
        if request.is_ajax():
            user_is_active_status = user.is_active
            return JsonResponse({"user_is_active_status": user_is_active_status})
        return HttpResponseRedirect(reverse("adminapp:get_users"))
    return HttpResponseRedirect(reverse("main:index"))


def change_user_role(request, pk, role):
    user = User.objects.filter(pk=pk).first()
    user.user_role = role
    user.save()

    if request.is_ajax():
        content = {
            "user": user,
        }
        return JsonResponse({"user_role": user.user_role})

    return HttpResponseRedirect(reverse("adminapp:get_users"))


def create_user(request):
    if request.method == "POST":
        form = AdminUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("adminapp:get_users"))
    else:
        form = AdminUserRegisterForm()
    context = {
        "title": "Регистрация пользователя",
        "form": form,
        "categories": get_category_list,
    }

    return render(request, "adminapp/users_creation_page.html", context)


def get_user_info(request, pk):
    user = User.objects.filter(pk=pk).first()
    if request.is_ajax():
        return JsonResponse(
            {
                "user": {
                    "user_id": pk,
                    "user_status": user.is_active,
                    "user_role": user.user_role
                }
            }
        )
    return JsonResponse({"user": {"user_id": pk, "user_status": user.is_active, "user_role": user.user_role}})


def search_ajax(request):
    search_request = request.GET.get("search_request")
    search_filter = request.GET.get("filter")
    if request.is_ajax():
        search_output = perform_search_ajax(search_request, search_filter)
        return JsonResponse({"search_output": search_output})
    return HttpResponseRedirect(reverse("adminapp:get_users"))

scrum/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="../../../static/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="../../../static/css/admin_style.css"/>
    {% endblock %}
</head>

<body class="container-fluid col-md-12" style="height: 100%;">
<header class="navbar mt-3 navbar-dark bg-dark " style="border-radius: 0.25rem 0.25rem 0 0;">
    <div class="d-flex justify-content-between text-white text-decoration-none col-md-2">
        <a class=""
           href="{% url 'main:index' %}">
            <button class="target_button target_button_green w-button shadow rounded mx-2" type="button">
                На главную
            </button>
        </a>
        <a class="l"
           href="{% url 'my_lk:my_profile' user.id %}">
            <button class="target_button target_button_green w-button shadow rounded mx-2" type="button">
                Мой профиль
            </button>
        </a>
    </div>
    <a class="navbar-brand my-1 mx-auto" href="{% url 'my_admin:get_users' %}">Управление порталом</a>
</header>
<main class="row mx-auto">
    <div class="d-flex flex-column flex-shrink-0 p-2 pt-0 text-white bg-dark col-md-2"
         style="border-radius: 0 0 0.25rem 0.25rem;">
        <hr class="m-0">
        <span class="fs-4 m-auto mt-0 mb-0">Панель меню</span>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto ">
            <li class="nav-item flex-fill d-flex justify-content-between admin_main_menu">
                <a href="{% url 'my_admin:get_users' %}" style="font-size: 14px;"
                   class="target_button target_button_blue menu_button w-button shadow rounded me-2
                        {% if request.path == '/my_admin/users/' %} active {% else %} text-white {% endif %}">
                    Пользователи
                </a>
                <a href="{% url 'adminapp:create_user' %}"
                   class="target_button target_button_blue target_icon w-button shadow rounded">
                    <img src="{% static '/vendor/img_for_admin/icon_add_user.png' %}" height="20px"
                         alt="Добавить пользователя" class="">
                </a>
            </li>
        </ul>

    </div>
    <div class="col-md-10 text-center admin-main-block">
        {% block main %}

        {% endblock %}
    </div>
</main>
<!-- <footer class="footer mt-auto py-3 bg-light">
</footer> -->
</body>
{% block js %}
    <script src="/static/js/bootstrap.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}

</html>

scrum/adminapp/templates/adminapp/categories_table_page.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block main %}
    <div> Таблица для категорий
        <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Название</th>
                <th scope="col">Создано</th>
                <th scope="col">Описание</th>
                <th scope="col">Активно</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>DevOps</td>
                <td>11.10.2021</td>
                <td>Раздел деплоев на сервер и прочих штук</td>
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Активно/Не активно</label>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    </div>
{% endblock %}

scrum/adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block main %}
    <h1>Главная страница админки</h1>
{% endblock %}

scrum/adminapp/templates/adminapp/posts_table_page.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block main %}
    <div> Таблица для постов
        <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Категория</th>
                <th scope="col">Заголовок</th>
                <th scope="col">Автор</th>
                <th scope="col">Создано</th>
                <th scope="col">Обновлено</th>
                <th scope="col">Активно</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>DevOps</td>
                <td>Разворачиваем docker на калькуляторе</td>
                <td>Илья Носов</td>
                <td>11.10.2021</td>
                <td>11.10.2021 в 17:12</td>
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Активно/Не активно</label>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    </div>
{% endblock %}

scrum/adminapp/templates/adminapp/users_creation_page.html
{% extends 'adminapp/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block main %}
    <div class="container-2 w-container p-5 mt-3 mb-5shadow rounded"
         style="width: 100%; margin-left: auto; margin-right: auto; max-width: 960px;">
        <div><h4>Регистрация нового пользователя</h4></div>
        <form method="post" enctype="multipart/form-data"
              class="mx-auto my-5 p-3 text-center rounded "
              style="max-width: 300px">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary my-auto mx-auto">
                Зарегистрировать
            </button>
            <button type="reset" class="btn btn-danger my-2 mx-auto">Сбросить
            </button>
        </form>
    </div>
{% endblock %}

scrum/adminapp/templates/adminapp/users_table_page.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block main %}
    {% include 'adminapp/includes/inc__search_users.html' %}
    <div class="admin_users_list">
        {% include 'adminapp/includes/inc__admin_users_list.html' %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="{% static 'js/user_control.js' %}"></script>
{% endblock %}